### ISSUE TITLE
Bump to version v0.1.3

### ISSUE THREAD

**Issue by MKaptein** [scailable/sclblonnx#2]
For the fix of https://github.com/scailable/sclblpy/commit/ee6d5eac0eff7e962f67a45caeef4d54c530f479, the `scull_input` function needed updating (adding missing quotes for the single input case).

With this change, and `sclblpy >= 0.1.7` the two packages can now be jointly used to immediately run created endpoints on the cloud without having to worry about the `I/O`

**Comment by robinvanemden** [comment]
Version bumped, pushed to PyPi.
