### ISSUE TITLE
How are missing optional inputs given?

### ISSUE THREAD

**Issue by kraiskil** [scailable/sclblonnx#26]
How do I tell sclblonnx that an optional input is missing?

I'm trying with the python code below. Its problem is that I don't provide all optional inputs to the LSTM node. Here `B` and `sequence_lens` input are missing, and so sclblonnx (or onnx-runtime) interpret the `initial_h` input as `B`.

Is it possible to tell which optional input I want an input to be, or must I provide all missing inputs with initialized default values?

My script:
```
import numpy as np
import sclblonnx as so

hidden_s=1
input_s=1
seq_len=1
batch_s=1
num_dir=1

x = np.array([1]).reshape([seq_len, batch_s, input_s])
w = np.array([1,1,1,1]).reshape([num_dir, 4*hidden_s, input_s])
r = np.array([1,1,1,1]).reshape([num_dir, 4*hidden_s, hidden_s])
init_h = np.array([42]).reshape([num_dir, batch_s, hidden_s])

print(x.shape)
print(w.shape)
print(r.shape)

g = so.empty_graph()
n1 = so.node('LSTM', inputs=['x', 'w', 'r', 'i_h'], outputs=['Y'], hidden_size=hidden_s)
g = so.add_node(g, n1)
g = so.add_input(g, 'x', "FLOAT", x.shape)
g = so.add_input(g, 'w', "FLOAT", w.shape)
g = so.add_input(g, 'r', "FLOAT", r.shape)
g = so.add_input(g, 'i_h', "FLOAT", init_h.shape)
g = so.add_output(g, 'Y', "FLOAT", [seq_len, num_dir, batch_s, hidden_s])


so.check(g)

example = {
	"x": x.astype(np.float32),
	"w": w.astype(np.float32),
	"r": r.astype(np.float32),
	"i_h": init_h.astype(np.float32)
}
result = so.run(g,
                inputs=example,
                outputs=["Y"]
                )
print(result)
```

**Comment by MKaptein** [comment]
Hi,

Yeah, this has been some fiddling for me before… I guess all inputs need to be specified, but I am a bit unsure so if you find a more workable solution please do share it!

**Comment by kraiskil** [comment]
Found it. ONNX manual says missing inputs should be given with a name of `""` (empty string).
Providing the empty names in the above script makes it work:
```
n1 = so.node('LSTM', inputs=['x', 'w', 'r','', '', 'i_h'], outputs=['Y'], hidden_size=hidden_s)
```

Verified to work with netron and onnx2c.
