### ISSUE TITLE
ERROR: The operator(s) ['ConstantOfShape', 'ConstantOfShape'] are currently not supported.

### ISSUE THREAD

**Issue by PCPJ** [scailable/sclblonnx#32]
Hi, sorry to bother with this.
I am trying to merge two onnx models, and when I try to import one of them (tiny yolo v4) I get this error message after the line
`sclblonnx.check(yolo_graph)`.
It doesn't make sense to me because apparently the `ConstantOfShape` operator is already supported: #28 
Thank you some much.

**Comment by MKaptein** [comment]
Hi, 

Are you sure you are using the latest version of the package? The support of "ConstantOfShape" is included in the list (see https://github.com/scailable/sclblonnx/blob/master/sclblonnx/supported_onnx.json) so this one should pass...

**Comment by PCPJ** [comment]
```
>>> import sclblonnx
>>> sclblonnx.__version__
'0.1.9'
>>> 

```
Isn't this the last version?

**Comment by PCPJ** [comment]
```

**Comment by ayoub-assis** [comment]
Hi @PCPJ, the latest version hasn't been pushed yet online to Pypi, you need to install it from github, use the following command:
`pip install git+https://github.com/scailable/sclblonnx --upgrade`

**Comment by PCPJ** [comment]
Thank you! Now it is working. Since my current version was 0.1.9 I thought that it was the latest version.
