### ISSUE TITLE
Update ONNX version compatibility

### ISSUE THREAD

**Issue by ntwilson** [scailable/sclblonnx#36]
This package requires ONNX version 1.8.1, but it would be really helpful for us to use this package with ONNX version 1.11.0, and the two appear to work together just fine in our testing.  What testing (if any) is involved with relaxing the ONNX version constraint, and would you accept a PR that relaxes it?

**Comment by MKaptein** [comment]
Hi,

There are some rudimentary tests in the /test folder, it would be nice if these don’t break. However, I expect the update to 1.11.0 will not be a problem at all, and yes, we would be happy receiving a PR! Great to have people contributing to this!

**Comment by ntwilson** [comment]
ONNX compatibility with 1.11.0 is on Pypi.  Sorry I forgot to link this issue from the PR.
