### ISSUE TITLE
How can I add other nodes  ？

### ISSUE THREAD

**Issue by monsterlyg** [scailable/sclblonnx#46]
The examples have shown how to use ops like "Sub","Abs"... .etc. How can I add those nodes in onnx definition， where can I find the attributes. Any doc i can refer to ?

**Comment by ayoub-assis** [comment]
Hi @monsterlyg, sorry for the late reply.

You can find operators definition in the [ONNX docs](https://github.com/onnx/onnx/blob/main/docs/Operators.md#operator-schemas). But, be mindful about the opset version of your ONNX graph, as an operator's specification varies from a version to another.
